server:
  port: 8764
spring:
  #rabbitmq:
  profiles:
    active: jdbc
  application:
    name: service-config
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      server:
        jdbc:
          sql: select akey, avalue from test where aapplication = ? and aprofile = ? and alabel = ?
      label: master
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.20.211:3306/test?characterEncoding=utf8
    username: kcash
    password: 08kCYF7Fefugqioq
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    web:
      exposure:
        include: bus-refresh