server:
  port: 8764

spring:
  profiles:
    active: jdbc
  application:
    name: service-config
  cloud:
    config:
      server:
        jdbc:
          sql: select akey, avalue from test
      label: master
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.20.211:3306/test?characterEncoding=utf8
    username: kcash
    password: 08kCYF7Fefugqioq

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/