server:
  port: 8762

spring:
  profiles:
    active: dev
  application:
    name: service-manager
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

name0:
  name00:
    name000: 我是service-user